# file: monit/tasks/main.yml

- name: Monit | Make sure monit is installed
  apt:
    pkg: monit
    state: present

- debug: msg="{{mapped_interface_1}}"
- debug: msg="{{groups['m_monit']}}"
- debug: msg="{{monit_mailserver_username}}"

- name: Monit | Update the monit configuration (/etc/monit/monitrc)
  template:
    src: "etc_monit_monitrc.j2"
    dest: "/etc/monit/monitrc"
  notify:
    - restart monit
                
# Ansible resolves the path relative to the roles/<rolename>/files directory
- name: Monit | Template the monit service files
  template:
    src: "{{item}}"
    dest: "/etc/monit/conf.d/{{item | basename | replace('etc_monit_conf.d_','') | replace('.j2','')}}"
    owner: "{{ansible_ssh_user}}"
    group: "{{ansible_ssh_user}}"
    mode: 0660
  with_fileglob: 
    - ../templates/etc_monit_conf.d_*
  notify:
    - restart monit

# - name: Set up service monitoring for all tagged services
#   set_fact: 
#     services="{{group_names | intersect(ansible_role_groups)}}"